/* Bibliography. Every formula or threshold in CVAN should trace back to one
   of these. Citations target permanent sources where possible (DOIs, NASA
   ADS, NCEI/SWPC services, IGRF). */

export const SOURCES = [
  {
    id: "meeus",
    title: "Astronomical Algorithms (2nd ed.)",
    author: "Jean Meeus",
    year: 1998,
    publisher: "Willmann-Bell",
    isbn: "978-0943396613",
    used: "Sun ephemeris (Ch. 25), Moon ephemeris (Ch. 47), sidereal time (Ch. 12), rise/set (Ch. 15), moon phase (Ch. 49).",
  },
  {
    id: "spa",
    title: "Solar Position Algorithm for Solar Radiation Applications",
    author: "Reda, I., & Andreas, A.",
    year: 2008,
    publisher: "NREL Technical Report TP-560-34302",
    url: "https://www.nrel.gov/docs/fy08osti/34302.pdf",
    used: "Cross-check for low-precision sun ephemeris and twilight thresholds.",
  },
  {
    id: "ks1991",
    title: "A Model of the Brightness of Moonlight",
    author: "Krisciunas, K., & Schaefer, B. E.",
    year: 1991,
    publisher: "PASP 103, 1033",
    doi: "10.1086/132921",
    url: "https://ui.adsabs.harvard.edu/abs/1991PASP..103.1033K/abstract",
    used: "Moon sky brightness model (lunar illuminance vs phase angle and altitude).",
  },
  {
    id: "bortle",
    title: "Introducing the Bortle Dark-Sky Scale",
    author: "Bortle, J. E.",
    year: 2001,
    publisher: "Sky & Telescope, Feb 2001",
    url: "https://skyandtelescope.org/astronomy-resources/light-pollution-and-astronomy-the-bortle-dark-sky-scale/",
    used: "Class definitions and qualitative Milky Way / DSO descriptions used for verdict text.",
  },
  {
    id: "falchi2016",
    title: "The new world atlas of artificial night sky brightness",
    author: "Falchi, F., Cinzano, P., Duriscoe, D., et al.",
    year: 2016,
    publisher: "Science Advances 2(6), e1600377",
    doi: "10.1126/sciadv.1600377",
    url: "https://www.science.org/doi/10.1126/sciadv.1600377",
    used: "Defines the artificial-to-natural sky brightness ratio framework that the Lorenz atlas tiles encode per pixel.",
  },
  {
    id: "viirsdnb",
    title: "VIIRS Day/Night Band Nightly Earth-Observation Group",
    author: "Elvidge, C. D., Zhizhin, M., Ghosh, T., et al.",
    year: 2021,
    publisher: "Remote Sens. 13, 922",
    doi: "10.3390/rs13050922",
    url: "https://eogdata.mines.edu/products/vnl/",
    used: "Underlying satellite radiance product used by the Lorenz atlas to derive artificial sky brightness.",
  },
  {
    id: "lorenz-lp-atlas",
    title: "World Atlas of Artificial Night Sky Brightness — annual VIIRS-derived tiles",
    author: "Lorenz, D. J.",
    publisher: "University of Wisconsin–Madison",
    url: "https://djlorenz.github.io/astronomy/lp/",
    used: "Live data source. Per-pixel artificial-to-natural sky brightness ratio (Light Pollution Index) sampled from the published 2024 atlas tiles, then converted to SQM and Bortle.",
  },
  {
    id: "swpc-kp",
    title: "Planetary K-index (1-minute estimated)",
    publisher: "NOAA SWPC",
    url: "https://services.swpc.noaa.gov/json/planetary_k_index_1m.json",
    used: "Real-time planetary Kp index (estimated_kp field).",
  },
  {
    id: "swpc-kp-forecast",
    title: "3-Day Geomagnetic Forecast (Planetary K)",
    publisher: "NOAA SWPC",
    url: "https://services.swpc.noaa.gov/products/noaa-planetary-k-index-forecast.json",
    used: "Predicted Kp at 3-hour resolution out to 3 days.",
  },
  {
    id: "swpc-ovation",
    title: "OVATION Aurora Forecast Model",
    author: "Newell, P. T., Sotirelis, T., & Wing, S.",
    year: 2014,
    publisher: "JGR Space Physics 119, 5751",
    doi: "10.1002/2014JA019921",
    url: "https://services.swpc.noaa.gov/json/ovation_aurora_latest.json",
    used: "Latitude-longitude grid of auroral activity probability used for the map overlay.",
  },
  {
    id: "swpc-aurora-tutorial",
    title: "Aurora Tutorial — Viewing Latitude vs Kp",
    publisher: "NOAA SWPC",
    url: "https://www.swpc.noaa.gov/content/tips-viewing-aurora",
    used: "Equatorward boundary of auroral oval as a function of Kp (KP_VIEW_LAT table).",
  },
  {
    id: "igrf13",
    title: "International Geomagnetic Reference Field, 13th generation",
    author: "Alken, P., Thébault, E., Beggan, C. D., et al.",
    year: 2021,
    publisher: "Earth Planets Space 73, 49",
    doi: "10.1186/s40623-020-01288-x",
    url: "https://www.ncei.noaa.gov/products/international-geomagnetic-reference-field",
    used: "Geomagnetic dipole pole position (epoch 2025) for geomagnetic latitude approximation.",
  },
  {
    id: "open-meteo",
    title: "Open-Meteo Weather Forecast API",
    publisher: "Open-Meteo",
    url: "https://open-meteo.com/",
    used: "Hourly cloud cover, visibility, temperature, humidity (16-day forecast horizon).",
  },
  {
    id: "nominatim",
    title: "Nominatim Geocoding",
    publisher: "OpenStreetMap Foundation",
    url: "https://nominatim.openstreetmap.org/",
    used: "City and place-name geocoding (free-text → coordinates).",
  },
  {
    id: "leaflet",
    title: "Leaflet — open-source JavaScript library for interactive maps",
    publisher: "Vladimir Agafonkin / Leaflet contributors",
    url: "https://leafletjs.com/",
    used: "Map widget for location picking and overlay rendering.",
  },
  {
    id: "osm",
    title: "OpenStreetMap",
    publisher: "OpenStreetMap contributors",
    url: "https://www.openstreetmap.org/copyright",
    used: "Base map tiles. Tile data © OSM contributors, ODbL.",
  },
  {
    id: "nasa-gibs",
    title: "NASA Global Imagery Browse Services (GIBS) — VIIRS SNPP daily true-color imagery",
    publisher: "NASA EOSDIS",
    url: "https://nasa-gibs.github.io/gibs-api-docs/",
    used: "Cloud-cover map overlay (latest near-real-time global satellite mosaic).",
  },
];
